// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ArenaService.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ArenaResultReply_ArenaMessageOut int32

const (
	ArenaResultReply_GOOD       ArenaResultReply_ArenaMessageOut = 0
	ArenaResultReply_BADMESSAGE ArenaResultReply_ArenaMessageOut = 1
	ArenaResultReply_COLLIZION  ArenaResultReply_ArenaMessageOut = 2
)

var ArenaResultReply_ArenaMessageOut_name = map[int32]string{
	0: "GOOD",
	1: "BADMESSAGE",
	2: "COLLIZION",
}
var ArenaResultReply_ArenaMessageOut_value = map[string]int32{
	"GOOD":       0,
	"BADMESSAGE": 1,
	"COLLIZION":  2,
}

func (x ArenaResultReply_ArenaMessageOut) String() string {
	return proto.EnumName(ArenaResultReply_ArenaMessageOut_name, int32(x))
}
func (ArenaResultReply_ArenaMessageOut) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ArenaService_84be1f0c08eac87c, []int{8, 0}
}

type BalanceRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceRequest) Reset()         { *m = BalanceRequest{} }
func (m *BalanceRequest) String() string { return proto.CompactTextString(m) }
func (*BalanceRequest) ProtoMessage()    {}
func (*BalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ArenaService_84be1f0c08eac87c, []int{0}
}
func (m *BalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceRequest.Unmarshal(m, b)
}
func (m *BalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceRequest.Marshal(b, m, deterministic)
}
func (dst *BalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceRequest.Merge(dst, src)
}
func (m *BalanceRequest) XXX_Size() int {
	return xxx_messageInfo_BalanceRequest.Size(m)
}
func (m *BalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceRequest proto.InternalMessageInfo

func (m *BalanceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type BalanceReply struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Balance              float32  `protobuf:"fixed32,2,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceReply) Reset()         { *m = BalanceReply{} }
func (m *BalanceReply) String() string { return proto.CompactTextString(m) }
func (*BalanceReply) ProtoMessage()    {}
func (*BalanceReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ArenaService_84be1f0c08eac87c, []int{1}
}
func (m *BalanceReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceReply.Unmarshal(m, b)
}
func (m *BalanceReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceReply.Marshal(b, m, deterministic)
}
func (dst *BalanceReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceReply.Merge(dst, src)
}
func (m *BalanceReply) XXX_Size() int {
	return xxx_messageInfo_BalanceReply.Size(m)
}
func (m *BalanceReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceReply.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceReply proto.InternalMessageInfo

func (m *BalanceReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BalanceReply) GetBalance() float32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type LoginRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ArenaService_84be1f0c08eac87c, []int{2}
}
func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (dst *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(dst, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginReply struct {
	TockenID             string   `protobuf:"bytes,1,opt,name=tockenID,proto3" json:"tockenID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReply) Reset()         { *m = LoginReply{} }
func (m *LoginReply) String() string { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()    {}
func (*LoginReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ArenaService_84be1f0c08eac87c, []int{3}
}
func (m *LoginReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReply.Unmarshal(m, b)
}
func (m *LoginReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReply.Marshal(b, m, deterministic)
}
func (dst *LoginReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReply.Merge(dst, src)
}
func (m *LoginReply) XXX_Size() int {
	return xxx_messageInfo_LoginReply.Size(m)
}
func (m *LoginReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReply.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReply proto.InternalMessageInfo

func (m *LoginReply) GetTockenID() string {
	if m != nil {
		return m.TockenID
	}
	return ""
}

func (m *LoginReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ArenaInitiateRequest struct {
	TockenID             string   `protobuf:"bytes,1,opt,name=tockenID,proto3" json:"tockenID,omitempty"`
	TockenArena          string   `protobuf:"bytes,2,opt,name=tockenArena,proto3" json:"tockenArena,omitempty"`
	TeamTocken           string   `protobuf:"bytes,3,opt,name=teamTocken,proto3" json:"teamTocken,omitempty"`
	Nick                 string   `protobuf:"bytes,4,opt,name=Nick,proto3" json:"Nick,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArenaInitiateRequest) Reset()         { *m = ArenaInitiateRequest{} }
func (m *ArenaInitiateRequest) String() string { return proto.CompactTextString(m) }
func (*ArenaInitiateRequest) ProtoMessage()    {}
func (*ArenaInitiateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ArenaService_84be1f0c08eac87c, []int{4}
}
func (m *ArenaInitiateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArenaInitiateRequest.Unmarshal(m, b)
}
func (m *ArenaInitiateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArenaInitiateRequest.Marshal(b, m, deterministic)
}
func (dst *ArenaInitiateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArenaInitiateRequest.Merge(dst, src)
}
func (m *ArenaInitiateRequest) XXX_Size() int {
	return xxx_messageInfo_ArenaInitiateRequest.Size(m)
}
func (m *ArenaInitiateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ArenaInitiateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ArenaInitiateRequest proto.InternalMessageInfo

func (m *ArenaInitiateRequest) GetTockenID() string {
	if m != nil {
		return m.TockenID
	}
	return ""
}

func (m *ArenaInitiateRequest) GetTockenArena() string {
	if m != nil {
		return m.TockenArena
	}
	return ""
}

func (m *ArenaInitiateRequest) GetTeamTocken() string {
	if m != nil {
		return m.TeamTocken
	}
	return ""
}

func (m *ArenaInitiateRequest) GetNick() string {
	if m != nil {
		return m.Nick
	}
	return ""
}

type ArenaFindRequest struct {
	TockenArena          string   `protobuf:"bytes,1,opt,name=tockenArena,proto3" json:"tockenArena,omitempty"`
	TeamTocken           string   `protobuf:"bytes,2,opt,name=teamTocken,proto3" json:"teamTocken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArenaFindRequest) Reset()         { *m = ArenaFindRequest{} }
func (m *ArenaFindRequest) String() string { return proto.CompactTextString(m) }
func (*ArenaFindRequest) ProtoMessage()    {}
func (*ArenaFindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ArenaService_84be1f0c08eac87c, []int{5}
}
func (m *ArenaFindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArenaFindRequest.Unmarshal(m, b)
}
func (m *ArenaFindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArenaFindRequest.Marshal(b, m, deterministic)
}
func (dst *ArenaFindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArenaFindRequest.Merge(dst, src)
}
func (m *ArenaFindRequest) XXX_Size() int {
	return xxx_messageInfo_ArenaFindRequest.Size(m)
}
func (m *ArenaFindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ArenaFindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ArenaFindRequest proto.InternalMessageInfo

func (m *ArenaFindRequest) GetTockenArena() string {
	if m != nil {
		return m.TockenArena
	}
	return ""
}

func (m *ArenaFindRequest) GetTeamTocken() string {
	if m != nil {
		return m.TeamTocken
	}
	return ""
}

type ArenaFindReply struct {
	NamesAlias           []string `protobuf:"bytes,1,rep,name=NamesAlias,proto3" json:"NamesAlias,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArenaFindReply) Reset()         { *m = ArenaFindReply{} }
func (m *ArenaFindReply) String() string { return proto.CompactTextString(m) }
func (*ArenaFindReply) ProtoMessage()    {}
func (*ArenaFindReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ArenaService_84be1f0c08eac87c, []int{6}
}
func (m *ArenaFindReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArenaFindReply.Unmarshal(m, b)
}
func (m *ArenaFindReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArenaFindReply.Marshal(b, m, deterministic)
}
func (dst *ArenaFindReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArenaFindReply.Merge(dst, src)
}
func (m *ArenaFindReply) XXX_Size() int {
	return xxx_messageInfo_ArenaFindReply.Size(m)
}
func (m *ArenaFindReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ArenaFindReply.DiscardUnknown(m)
}

var xxx_messageInfo_ArenaFindReply proto.InternalMessageInfo

func (m *ArenaFindReply) GetNamesAlias() []string {
	if m != nil {
		return m.NamesAlias
	}
	return nil
}

type ArenaResultRequest struct {
	TockenID             string   `protobuf:"bytes,1,opt,name=tockenID,proto3" json:"tockenID,omitempty"`
	TockenArena          string   `protobuf:"bytes,2,opt,name=tockenArena,proto3" json:"tockenArena,omitempty"`
	TeamTocken           string   `protobuf:"bytes,3,opt,name=teamTocken,proto3" json:"teamTocken,omitempty"`
	Nick                 string   `protobuf:"bytes,4,opt,name=Nick,proto3" json:"Nick,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArenaResultRequest) Reset()         { *m = ArenaResultRequest{} }
func (m *ArenaResultRequest) String() string { return proto.CompactTextString(m) }
func (*ArenaResultRequest) ProtoMessage()    {}
func (*ArenaResultRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ArenaService_84be1f0c08eac87c, []int{7}
}
func (m *ArenaResultRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArenaResultRequest.Unmarshal(m, b)
}
func (m *ArenaResultRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArenaResultRequest.Marshal(b, m, deterministic)
}
func (dst *ArenaResultRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArenaResultRequest.Merge(dst, src)
}
func (m *ArenaResultRequest) XXX_Size() int {
	return xxx_messageInfo_ArenaResultRequest.Size(m)
}
func (m *ArenaResultRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ArenaResultRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ArenaResultRequest proto.InternalMessageInfo

func (m *ArenaResultRequest) GetTockenID() string {
	if m != nil {
		return m.TockenID
	}
	return ""
}

func (m *ArenaResultRequest) GetTockenArena() string {
	if m != nil {
		return m.TockenArena
	}
	return ""
}

func (m *ArenaResultRequest) GetTeamTocken() string {
	if m != nil {
		return m.TeamTocken
	}
	return ""
}

func (m *ArenaResultRequest) GetNick() string {
	if m != nil {
		return m.Nick
	}
	return ""
}

type ArenaResultReply struct {
	MessageOut           ArenaResultReply_ArenaMessageOut `protobuf:"varint,1,opt,name=MessageOut,proto3,enum=protobuf.ArenaResultReply_ArenaMessageOut" json:"MessageOut,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *ArenaResultReply) Reset()         { *m = ArenaResultReply{} }
func (m *ArenaResultReply) String() string { return proto.CompactTextString(m) }
func (*ArenaResultReply) ProtoMessage()    {}
func (*ArenaResultReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ArenaService_84be1f0c08eac87c, []int{8}
}
func (m *ArenaResultReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArenaResultReply.Unmarshal(m, b)
}
func (m *ArenaResultReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArenaResultReply.Marshal(b, m, deterministic)
}
func (dst *ArenaResultReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArenaResultReply.Merge(dst, src)
}
func (m *ArenaResultReply) XXX_Size() int {
	return xxx_messageInfo_ArenaResultReply.Size(m)
}
func (m *ArenaResultReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ArenaResultReply.DiscardUnknown(m)
}

var xxx_messageInfo_ArenaResultReply proto.InternalMessageInfo

func (m *ArenaResultReply) GetMessageOut() ArenaResultReply_ArenaMessageOut {
	if m != nil {
		return m.MessageOut
	}
	return ArenaResultReply_GOOD
}

func init() {
	proto.RegisterType((*BalanceRequest)(nil), "protobuf.BalanceRequest")
	proto.RegisterType((*BalanceReply)(nil), "protobuf.BalanceReply")
	proto.RegisterType((*LoginRequest)(nil), "protobuf.LoginRequest")
	proto.RegisterType((*LoginReply)(nil), "protobuf.LoginReply")
	proto.RegisterType((*ArenaInitiateRequest)(nil), "protobuf.ArenaInitiateRequest")
	proto.RegisterType((*ArenaFindRequest)(nil), "protobuf.ArenaFindRequest")
	proto.RegisterType((*ArenaFindReply)(nil), "protobuf.ArenaFindReply")
	proto.RegisterType((*ArenaResultRequest)(nil), "protobuf.ArenaResultRequest")
	proto.RegisterType((*ArenaResultReply)(nil), "protobuf.ArenaResultReply")
	proto.RegisterEnum("protobuf.ArenaResultReply_ArenaMessageOut", ArenaResultReply_ArenaMessageOut_name, ArenaResultReply_ArenaMessageOut_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ArenaClient is the client API for Arena service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ArenaClient interface {
	// Sends a greeting
	SayBalance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceReply, error)
	LogIn(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
	ArenaInitiate(ctx context.Context, in *ArenaInitiateRequest, opts ...grpc.CallOption) (*ArenaFindReply, error)
	ArenaFind(ctx context.Context, in *ArenaFindRequest, opts ...grpc.CallOption) (*ArenaFindReply, error)
	ArenaResult(ctx context.Context, in *ArenaResultRequest, opts ...grpc.CallOption) (*ArenaResultReply, error)
}

type arenaClient struct {
	cc *grpc.ClientConn
}

func NewArenaClient(cc *grpc.ClientConn) ArenaClient {
	return &arenaClient{cc}
}

func (c *arenaClient) SayBalance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceReply, error) {
	out := new(BalanceReply)
	err := c.cc.Invoke(ctx, "/protobuf.Arena/SayBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arenaClient) LogIn(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := c.cc.Invoke(ctx, "/protobuf.Arena/LogIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arenaClient) ArenaInitiate(ctx context.Context, in *ArenaInitiateRequest, opts ...grpc.CallOption) (*ArenaFindReply, error) {
	out := new(ArenaFindReply)
	err := c.cc.Invoke(ctx, "/protobuf.Arena/ArenaInitiate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arenaClient) ArenaFind(ctx context.Context, in *ArenaFindRequest, opts ...grpc.CallOption) (*ArenaFindReply, error) {
	out := new(ArenaFindReply)
	err := c.cc.Invoke(ctx, "/protobuf.Arena/ArenaFind", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arenaClient) ArenaResult(ctx context.Context, in *ArenaResultRequest, opts ...grpc.CallOption) (*ArenaResultReply, error) {
	out := new(ArenaResultReply)
	err := c.cc.Invoke(ctx, "/protobuf.Arena/ArenaResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArenaServer is the server API for Arena service.
type ArenaServer interface {
	// Sends a greeting
	SayBalance(context.Context, *BalanceRequest) (*BalanceReply, error)
	LogIn(context.Context, *LoginRequest) (*LoginReply, error)
	ArenaInitiate(context.Context, *ArenaInitiateRequest) (*ArenaFindReply, error)
	ArenaFind(context.Context, *ArenaFindRequest) (*ArenaFindReply, error)
	ArenaResult(context.Context, *ArenaResultRequest) (*ArenaResultReply, error)
}

func RegisterArenaServer(s *grpc.Server, srv ArenaServer) {
	s.RegisterService(&_Arena_serviceDesc, srv)
}

func _Arena_SayBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArenaServer).SayBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Arena/SayBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArenaServer).SayBalance(ctx, req.(*BalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Arena_LogIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArenaServer).LogIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Arena/LogIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArenaServer).LogIn(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Arena_ArenaInitiate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArenaInitiateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArenaServer).ArenaInitiate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Arena/ArenaInitiate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArenaServer).ArenaInitiate(ctx, req.(*ArenaInitiateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Arena_ArenaFind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArenaFindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArenaServer).ArenaFind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Arena/ArenaFind",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArenaServer).ArenaFind(ctx, req.(*ArenaFindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Arena_ArenaResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArenaResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArenaServer).ArenaResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Arena/ArenaResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArenaServer).ArenaResult(ctx, req.(*ArenaResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Arena_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.Arena",
	HandlerType: (*ArenaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayBalance",
			Handler:    _Arena_SayBalance_Handler,
		},
		{
			MethodName: "LogIn",
			Handler:    _Arena_LogIn_Handler,
		},
		{
			MethodName: "ArenaInitiate",
			Handler:    _Arena_ArenaInitiate_Handler,
		},
		{
			MethodName: "ArenaFind",
			Handler:    _Arena_ArenaFind_Handler,
		},
		{
			MethodName: "ArenaResult",
			Handler:    _Arena_ArenaResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ArenaService.proto",
}

func init() { proto.RegisterFile("ArenaService.proto", fileDescriptor_ArenaService_84be1f0c08eac87c) }

var fileDescriptor_ArenaService_84be1f0c08eac87c = []byte{
	// 470 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x53, 0xcd, 0x6e, 0xd3, 0x40,
	0x18, 0xcc, 0xba, 0x29, 0x24, 0xd3, 0x36, 0x44, 0x9f, 0x2a, 0x64, 0x59, 0x28, 0x8a, 0x56, 0x1c,
	0x2a, 0x0e, 0x11, 0x2a, 0x07, 0x24, 0x54, 0x21, 0xd2, 0xa6, 0x54, 0x86, 0x34, 0x96, 0x9c, 0x9e,
	0xb8, 0x6d, 0xd2, 0x25, 0xb2, 0xea, 0xd8, 0x21, 0xde, 0x80, 0xf2, 0x02, 0x88, 0x67, 0xe0, 0xe5,
	0x78, 0x15, 0xe4, 0xf5, 0x4f, 0xb6, 0x26, 0x6d, 0x8e, 0x9c, 0xbc, 0x3b, 0x3b, 0x33, 0xdf, 0xf8,
	0xdb, 0x6f, 0x41, 0xfd, 0xa5, 0x8c, 0xc4, 0x58, 0x2e, 0xbf, 0x07, 0x53, 0xd9, 0x5b, 0x2c, 0x63,
	0x15, 0x53, 0x43, 0x7f, 0x26, 0xab, 0xaf, 0xfc, 0x25, 0x5a, 0xe7, 0x22, 0x14, 0xd1, 0x54, 0xfa,
	0xf2, 0xdb, 0x4a, 0x26, 0x8a, 0x08, 0xf5, 0x48, 0xcc, 0xa5, 0xcd, 0xba, 0xec, 0xa4, 0xe9, 0xeb,
	0x35, 0x3f, 0xc3, 0x61, 0xc9, 0x5a, 0x84, 0xeb, 0x6d, 0x1c, 0xb2, 0xf1, 0x74, 0x92, 0x71, 0x6c,
	0xab, 0xcb, 0x4e, 0x2c, 0xbf, 0xd8, 0xf2, 0xf7, 0x38, 0x1c, 0xc6, 0xb3, 0x20, 0x7a, 0xa4, 0x02,
	0x39, 0x68, 0x2c, 0x44, 0x92, 0xfc, 0x88, 0x97, 0xb7, 0x5a, 0xde, 0xf4, 0xcb, 0x3d, 0x3f, 0x03,
	0x72, 0x7d, 0x5a, 0xdb, 0x41, 0x43, 0xc5, 0xd3, 0x3b, 0x19, 0xb9, 0x83, 0xdc, 0xa1, 0xdc, 0x97,
	0xce, 0x96, 0x91, 0xfd, 0x17, 0xc3, 0xb1, 0x6e, 0x81, 0x1b, 0x05, 0x2a, 0x10, 0xaa, 0xfc, 0xd1,
	0xc7, 0x8c, 0xba, 0x38, 0xc8, 0xd6, 0x5a, 0x99, 0xfb, 0x99, 0x10, 0x75, 0x00, 0x25, 0xc5, 0xfc,
	0x46, 0x43, 0xf6, 0x9e, 0x26, 0x18, 0x48, 0x1a, 0x65, 0x14, 0x4c, 0xef, 0xec, 0x7a, 0x16, 0x25,
	0x5d, 0xf3, 0x1b, 0xb4, 0xb5, 0xf8, 0x63, 0x10, 0xdd, 0x16, 0x29, 0x2a, 0x95, 0xd8, 0xae, 0x4a,
	0x56, 0xb5, 0x12, 0x7f, 0x8d, 0x96, 0xe1, 0x9a, 0xb6, 0xa8, 0x03, 0x8c, 0xc4, 0x5c, 0x26, 0xfd,
	0x30, 0x10, 0x89, 0xcd, 0xba, 0x7b, 0xa9, 0x62, 0x83, 0xf0, 0x9f, 0x2c, 0x9f, 0x0a, 0x5f, 0x26,
	0xab, 0x50, 0xfd, 0xbf, 0x86, 0xfc, 0x66, 0x79, 0x47, 0x8a, 0x20, 0x69, 0xfa, 0x4f, 0xc0, 0xb5,
	0x4c, 0x12, 0x31, 0x93, 0xde, 0x4a, 0xe9, 0x20, 0xad, 0xd3, 0x57, 0xbd, 0x62, 0x62, 0x7b, 0x55,
	0x7e, 0x06, 0x6c, 0x14, 0xbe, 0xa1, 0xe6, 0xef, 0xf0, 0xac, 0x72, 0x4c, 0x0d, 0xd4, 0xaf, 0x3c,
	0x6f, 0xd0, 0xae, 0x51, 0x0b, 0x38, 0xef, 0x0f, 0xae, 0x2f, 0xc7, 0xe3, 0xfe, 0xd5, 0x65, 0x9b,
	0xd1, 0x11, 0x9a, 0x17, 0xde, 0x70, 0xe8, 0x7e, 0x71, 0xbd, 0x51, 0xdb, 0x3a, 0xfd, 0x63, 0x61,
	0x3f, 0xfb, 0xb5, 0x0f, 0xc0, 0x58, 0xac, 0xf3, 0x17, 0x40, 0xf6, 0x26, 0xcb, 0xfd, 0xa7, 0xe3,
	0x3c, 0xdf, 0x72, 0xb2, 0x08, 0xd7, 0xbc, 0x46, 0x6f, 0xb1, 0x3f, 0x8c, 0x67, 0x6e, 0x44, 0x06,
	0xc5, 0x7c, 0x13, 0xce, 0xf1, 0x3f, 0x78, 0x26, 0xfc, 0x8c, 0xa3, 0x7b, 0xc3, 0x4b, 0x9d, 0x4a,
	0x27, 0x2a, 0x53, 0xed, 0xd8, 0x95, 0xf3, 0x72, 0x2a, 0x78, 0x8d, 0x2e, 0xd0, 0x2c, 0x31, 0x72,
	0xb6, 0x12, 0x77, 0x9b, 0xb8, 0x38, 0x30, 0xae, 0x80, 0x5e, 0x3c, 0x70, 0x33, 0x99, 0x91, 0xf3,
	0xf0, 0xbd, 0xf1, 0xda, 0xe4, 0x89, 0x3e, 0x7c, 0xf3, 0x37, 0x00, 0x00, 0xff, 0xff, 0xf8, 0xda,
	0xfd, 0xd9, 0xa3, 0x04, 0x00, 0x00,
}
